app = "rogue1-signaling"
primary_region = "iad"

[build]

[http_service]
  internal_port = 9090
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
